### ISSUE TITLE
Error attempting to run after clone

### ISSUE THREAD

**Issue by douglasrafael** [nutes-uepb/haniot-dashboard#1]
**Describe the bug**
When executing the `npm run start:dev` command, the compilation process fails:
`ERROR Can not find module 'environments/environment'`. The same goes for `npm start`.

**Possible Solution**
Atualizar os scripts em package.json
```json
  "scripts": {
    "ng": "ng",
    "prestart": "npm run env",
    "prebuild": "npm run env",
    "start": "ng serve",
    "start:dev": "npm start",
    "start:prod": "npm run build && node server.js",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "env": "node generate-env.js"
  }
```

**Comment by AdalcinoJunior** [comment]
Scripts in package.json updated.

Solved in commit https://github.com/nutes-uepb/haniot-dashboard/commit/be041e760ba1f823ed0dd32a88240dc314de075c
